---
title: "Water Chemistry"
author: "Mariah Kachmar"
date: "2026-05-11"
output: html_document
description: 
---


#Set working directory
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = 'C:/Users/mariah.kachmar/documents/Github/EAD-ASEB_EPA_LISS_Disease_Surveillance') #Mariah's
#knitr::opts_knit$set(root.dir = 'C:/Users/kyra.lenderman/documents/Github/EAD-ASEB_EPA_LISS_Disease_Surveillance') #Kyra's
#knitr::opts_knit$set(root.dir = 'C:/Users/sarina.dery/documents/Github/EAD-ASEB_EPA_LISS_Disease_Surveillance') #Kelly's
```

#run packages
```{r}
library("ggplot2")
library("readxl")
library("plyr")                                     
library("dplyr")
library("Rmisc")
library("readr")  
library("lubridate")
library("purrr")
library(reshape2)
library(stringr)
library("RColorBrewer")
library("stringr")
library("tidyverse")
library(ggh4x)
library(wacolors)
library(glmm)
library(glmmTMB)
library(effectsize)
library("mgcv")
library("car")
```

#Set Path
```{r}
path_out <- 'Field_Data_WaterChemistry/output/'
```

#read data files
```{r}
data_all <- list.files(path = "Field_Data_WaterChemistry/raw_data",                           # Identify all CSV files
  pattern = "*.csv", full.names = TRUE) %>% 
  lapply(read_csv) %>%                              # Store all files in list
  bind_rows                                         # Combine data sets into one data set 
data_all                                            # Print data to RStudio console

as.data.frame(data_all)                            # Convert tibble to data.frame


#dates - adding month and year

data_all <- data_all %>% rename(c("date_collected" = "Date collected", "site" = "Location" )) %>% filter (site != "Laurel Hollow")

#for some reason not all of the dates are cooperating need to fix this for below****
data_all <- data_all %>% dplyr::mutate(date_collected= as.Date(date_collected, format = "%m/%d/%Y"), month = month(date_collected), year = year(date_collected))

data_all



```

#Aragonite Saturation ('WAr out')
```{r}

aragonite_master_long<- data_all %>%  
                      reshape2::melt(id.vars = c("date_collected", "site","month","year"),
                                    measure.vars = c("Salinity","t(oC) of field","pH out","pCO2 out (matm)","HCO3 out (mmol/kgSW)","CO3 out (mmol/kgSW)","CO2 out (mmol/kgSW)","WAr out","xCO2 out (dry at 1 atm) (ppm)"))
head(aragonite_master_long)

aragonite_master_long <- aragonite_master_long %>% filter(site != "Laurel Hollow")

monthly_aragonite_plot <- ggplot(data=aragonite_master_long %>% 
          filter(variable == "WAr out"), aes(x=month, y=value, fill=site)) +geom_point()+ #scale_fill_manual(values=c("forestgreen","orange", "purple"))
  theme_bw() + theme(plot.title = element_text(size = 20))+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  theme(axis.text.x = element_text(size = 12),
        axis.title.x = element_text(size = 12))+
  theme(axis.text.y = element_text(size = 12),
        axis.title.y = element_text(size =15))+
  labs(title="Monthly Aragonite Saturation", x ="", y = "Aragonite Sauration (Ωar)")+
  scale_y_continuous(limits = c(0,2), breaks = seq(0, 2, by = 0.2))+
  scale_x_continuous(breaks = 1:12) +
theme(strip.text = element_text(size = 12))+theme(legend.position = "none")+
  geom_hline(yintercept = 1, color = "red", size = .5) +  #red line is at equilibrium 
facet_grid(site ~ year, scales = "free_x", space = "free_x")

monthly_aragonite_plot

mean_aragonite_plot <- ggplot(
  data = aragonite_master_long %>%
    filter(variable == "WAr out"),
  aes(x = factor(year), y = value, fill = site)
) +
  geom_boxplot() +
  theme_bw() +
  theme(
    plot.title = element_text(size = 20),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.text.x = element_text(size = 12),
    axis.title.x = element_text(size = 12),
    axis.text.y = element_text(size = 12),
    axis.title.y = element_text(size = 15),
    strip.text = element_text(size = 12)
  ) +
  labs(
    title = "Mean Yearly Aragonite Saturation ",
    x = "Year",
    y = "Aragonite Saturation (Ωar)"
  ) +
  scale_y_continuous(
    limits = c(0, 2),
    breaks = seq(0, 2, by = 0.2)
  ) +
  geom_hline(yintercept = 1, color = "red", size = 0.5) +
  facet_wrap(~site)

mean_aragonite_plot

pdf(paste0(path = "Field_Data_WaterChemistry/output" ,"/Mean_Aragonite__all.pdf"), height = 7, width = 13)
print(mean_aragonite_plot)
dev.off()
```

# IGNORE THIS CODE FOR NOW NEED TO FIX
```{r}

data_all$month_abb <- factor(data_all$month,
                             levels = 1:12,
                             labels = month.abb)

ASHC_aragonite_temp_plot <-  data_all %>%
  dplyr::filter(site == "Ash Creek")%>%
  ggplot(aes(x = `t(oC) of field`,y = `WAr out`,color = site)) +
  geom_point( alpha = 0.7, size = 2) +
  scale_color_manual(values = c("Ash Creek" = "maroon"))+
  ggh4x::facet_nested(~year+month_abb, scales = "free", switch = "x")+
  geom_smooth(method= "lm", se= FALSE)+
  theme_minimal() + theme(ggh4x.facet.nestline=element_line(colour = "black"))+
  theme(panel.grid = element_line(colour = "white"), axis.text.x = element_blank(),axis.text = element_text(size= 15), axis.title = element_text(size = 20), strip.text = element_text(size = 15),legend.title= element_blank(),legend.text = element_text(size = 15), title = element_text(size = 25), axis.title.y = element_text(vjust = 2.5),axis.title.x = element_text(vjust = -1)) +
  labs(title = "Aragonite Saturation vs Temperature", x = "", y = "") + scale_y_continuous(limits = c(0, 2),breaks = seq(0, 2, by = 0.2)) +
  geom_hline(yintercept = 1, color = "red", size = 0.5)# +
  #facet_wrap(site, scales = "free")

ASHC_aragonite_temp_plot

FENC_aragonite_temp_plot <- data_all %>%
  dplyr::filter(site == "Fence Creek")%>% ggplot(
  aes(x = `t(oC) of field`,y = `WAr out`,color = site)) +
  geom_point( alpha = 0.7, size = 2)+
scale_color_manual(values = c("Fence Creek" = "darkgreen"))+
  ggh4x::facet_nested(~year+month_abb, scales = "free", switch = "x")+
  geom_smooth(method= "lm", se= FALSE)+
  theme_minimal() + theme(ggh4x.facet.nestline=element_line(colour = "black"))+
  theme(panel.grid = element_line(colour = "white"), axis.text.x = element_blank(),axis.text = element_text(size= 15), axis.title = element_text(size = 20), strip.text = element_text(size = 15),legend.title= element_blank(),legend.text = element_text(size = 15), title = element_text(size = 25), axis.title.y = element_text(vjust = 2.5),axis.title.x = element_text(vjust = -1)) +
  labs(title = "", x = "", y = "Aragonite Saturation (Ωar)") + scale_y_continuous(limits = c(0, 2),breaks = seq(0, 2, by = 0.2)) +
  geom_hline(yintercept = 1, color = "red", size = 0.5)# +
  #facet_wrap(site, scales = "free")

FENC_aragonite_temp_plot


GOLD_aragonite_temp_plot <- data_all %>%
  dplyr::filter(site == "Gold Star")%>%
  ggplot( aes(x = `t(oC) of field`,y = `WAr out`,color = site)) +
  geom_point( alpha = 0.7, size = 2)+
  scale_color_manual(values = c("Gold Star" = "steelblue"))+
  ggh4x::facet_nested(~year+month_abb, scales = "free", switch = "x")+
  geom_smooth(method= "lm", se= FALSE)+
  theme_minimal() + theme(ggh4x.facet.nestline=element_line(colour = "black")) +
  theme(panel.grid = element_line(colour = "white"), axis.text.x = element_blank(),axis.text = element_text(size= 15), axis.title = element_text(size = 20), strip.text = element_text(size = 15),legend.title= element_blank(),legend.text = element_text(size = 15), title = element_text(size = 25), axis.title.y = element_text(vjust = 2.5),axis.title.x = element_text(vjust = -1)) +
  labs(title = "", x = "Temperature (°C)", y = "") + scale_y_continuous(limits = c(0, 2),breaks = seq(0, 2, by = 0.2)) +
  geom_hline(yintercept = 1, color = "red", size = 0.5)# +
  #facet_wrap(site, scales = "free")

GOLD_aragonite_temp_plot


all_aragonite_temp <- ggarrange(ASHC_aragonite_temp_plot,FENC_aragonite_temp_plot,GOLD_aragonite_temp_plot, ncol=1)
all_aragonite_temp



pdf(paste0(path = "Field_Data_WaterChemistry/output" ,"/Aragonite_temperature_all.pdf"), height = 11, width = 14)
print(all_aragonite_temp)
dev.off()


```
#Aragonite vs Temperature
```{r}

Aragonite_temp_plot <-  data_all %>%
  ggplot(aes(x = `t(oC) of field`,y = `WAr out`,color = site)) +
  geom_point( alpha = 0.7, size = 2) +
  scale_color_manual(values = c("Ash Creek" = "maroon", "Fence Creek" = "darkgreen", "Gold Star" = "steelblue"))+
  geom_smooth(method= "lm", se= FALSE)+
  theme_bw()+
  theme(panel.grid = element_line(colour = "white"),axis.text = element_text(size= 15), axis.title = element_text(size = 20), strip.text = element_text(size = 15),legend.title= element_blank(),legend.text = element_text(size = 15), title = element_text(size = 25), axis.title.y = element_text(vjust = 2.5),axis.title.x = element_text(vjust = -1)) +
  labs(title = "Aragonite Saturation vs Temperature", x = "", y = "") + scale_y_continuous(limits = c(0, 2),breaks = seq(0, 2, by = 0.2)) + scale_x_continuous(limits = c(0,30))+
  geom_hline(yintercept = 1, color = "red", size = 0.5) #+
  #facet_wrap(site, scales = "free_x")

Aragonite_temp_plot

pdf(paste0(path = "Field_Data_WaterChemistry/output" ,"/Aragonite_temperature_all.pdf"), height = 11, width = 14)
print(Aragonite_temp_plot)
dev.off()

```

#lets do some quick stats to see what the relatioships are and differences between sites/time
```{r}

data_all <- data_all %>% filter(site != "Laurel Hollow")

glm_aragonite <- glmmTMB(`WAr out` ~ `t(oC) of field` + site * month,data_all)
summary(glm_aragonite)

glm_aragonite_pH <- glmmTMB(`WAr out` ~ `pH out` + site * month,data_all)
summary(glm_aragonite_pH)

```