---
title: "Raw_plotting_HOBO"
author: "Mariah Kachmar"
date: "1/19/2024"
output: html_document

---

Last updated: 4/4/25 M.Kachmar


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = 'C:/Users/mariah.kachmar/Documents/Github/EAD-ASEB_EPA_LISS_Disease_Surveillance') #Mariah's
#knitr::opts_knit$set(root.dir = 'C:/Users/kyra.lenderman/Documents/Github/EAD-ASEB_EPA_LISS_Disease_Surveillance') #Kyra's
#knitr::opts_knit$set(root.dir = 'C:/Users/kelly.roper/Documents/Github/EAD-ASEB_EPA_LISS_Disease_Surveillance')  #Kelly's
```


#### Load libraries

```{r load_libraries, include = TRUE}
# load libraries - notes show the install command needed to install (pre installed)
# Plotting
library(ggplot2)
library(dplyr)
library(gplots)
library(RColorBrewer)
library(ggpubr)
library(stringr)
library(lubridate)
library(readr)
library(reshape2)
library(readr)
library(tidyr)
library(data.table)
```

#Set Path
```{r}
path_out <- 'HOBO_Data/output/'
```


#### Fence Creek ####
# We had to change out the HOBO due to it breaking in June 2024 - there will be a gap in data due to this
```{r}
#Clean up and merged data sheets
df1<-read_csv("HOBO_Data\\raw_data\\062024_FENC_HOBO.csv", col_names = TRUE)%>% # do not change this df 2023-2024 data before we changed out the HOBO
  dplyr::select( -c("Host Connected", "Water Detect", "Button Down", "Button Up", "End of File"))%>% 
  dplyr::rename(Temperature = `Ch:1 - Temperature   (°C)`) %>%
  dplyr::rename(Date_Time = `Date-Time (EST/EDT)`)

df2<-read_csv("HOBO_Data\\raw_data\\042025_FENC_HOBO.csv", col_names = TRUE)%>%  # update this csv when new data comes in from the new HOBO
  dplyr::rename(Temperature = `Temperature`) %>%
  dplyr::rename(Date_Time = `Date-Time (EST/EDT)`)# %>%
  #dplyr::select( -c( "Button Down", "Button Up", "End of File", "Started Offset"))

FENC_HOBO <- rbind(df1,df2)   #Combine the two data sheets

as.data.frame(FENC_HOBO) #make a data frame


#Date formatting

FENC_HOBO$Date_Time <- as.character(FENC_HOBO$Date_Time)
date_time <- strsplit(FENC_HOBO$Date_Time, " ")  # Split at the space
FENC_HOBO$Date <- sapply(date_time, "[[", 1)  # Extract date
FENC_HOBO$Time <- sapply(date_time, function(x) {
  if(length(x) >= 2) {
    x[[2]]  # Extract the second element if it exists
  } else {
    NA  # Assign NA if the vector is too short
  }
})
print(FENC_HOBO)

#remove NAs
FENC_HOBO <- na.omit(FENC_HOBO)

#### Lets look at the data 

ggplot(FENC_HOBO, aes(Date_Time, Temperature)) + geom_point()


# Hourly Means 

FENC_means <- FENC_HOBO %>%
  mutate(Date_Time = as.POSIXct(substr(Date_Time, 1, 13), format = "%m/%d/%Y %H")) %>% # Adjust the date format
  tidyr::pivot_longer(cols = c("Temperature"), names_to = "variable", values_to = "value") %>%
  dplyr::group_by(Date_Time, variable) %>%
  dplyr::summarise(mean_value = mean(value),sd_value = sd(value),se_value = sd(value) / sqrt(n())) 

FENC_means

View(FENC_means)

FENC_means_2024 <- FENC_means %>% filter(Date_Time > '2024-04-01 00:00:00' & Date_Time < '2024-11-30 00:00:00' )
```

```{r}
FENC_plot<- FENC_means %>%
    ggplot(aes(Date_Time, mean_value))+ geom_point() + 
    geom_line(size = 0.2, position=position_dodge(.4))+
    #scale_color_manual(values = "grey38")+
              scale_shape_manual(values=c(21, 22, 24, 25)) + 
              scale_fill_manual(values=c("#CC79A7", "#D55E00", "#009E73", "#0072B2")) + 
              geom_errorbar(aes(ymin=(mean_value)-(se_value), 
                                ymax=(mean_value)+(se_value)), 
                            width=0,position=position_dodge(.4))+
     ggtitle("Fence Creek, CT ") +
              #labs(x = "Time", y = "Temperature") +
               labs(x = "", y = "") + 
              theme_classic() + theme(axis.text= element_text(size=12), axis.title = element_text(size= 12))+
   scale_x_datetime(date_labels = "%b/%Y", date_breaks = "1 month")
FENC_plot

FENC_plot <- FENC_means %>%
    mutate(Date_Time = as.POSIXct(Date_Time)) %>%
    ggplot(aes(Date_Time, mean_value)) + 
    geom_point() + 
    geom_line(size = 0.2, position = position_dodge(.4)) +
    scale_shape_manual(values = c(21, 22, 24, 25)) + 
    scale_fill_manual(values = c("#CC79A7", "#D55E00", "#009E73", "#0072B2")) + 
    geom_errorbar(aes(ymin = mean_value - se_value, 
                      ymax = mean_value + se_value), 
                  width = 0, position = position_dodge(.4)) +
    ggtitle("Fence Creek, CT") +
    labs(x = "", y = "") + 
    theme_classic() + 
    theme(axis.text = element_text(size = 25), axis.title = element_text(size = 12),axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1) ) +
    scale_x_datetime(date_labels = "%b/%Y", 
                     date_breaks = "1 month", 
                     limits = as.POSIXct(c('2023-06-01', '2025-11-30')))+geom_hline(yintercept = 20, color = "red", linetype = "solid", size = 1)+
  geom_hline(yintercept = 16, color = "blue", linetype = "solid", size = 1)
FENC_plot

pdf(paste0(path_out,"FENC_HOBO.pdf"), height = 7, width = 14)
print(FENC_plot)

```

#### Ash Creek ####
```{r}
#Clean up and merged data sheets
#072024_ASHC_HOBO - has data from 7/2023 to 7/2024
df3<-read_csv("HOBO_Data\\raw_data\\072024_ASHC_HOBO.csv", col_names = TRUE)%>% # do not change this df 2023-2024 data before we changed out the HOBO
  dplyr::select( -c("Host Connected", "Button Down", "Button Up", "End of File"))%>% 
  dplyr::rename(Temperature = `Ch:1 - Temperature   (°C)`) %>%
  dplyr::rename(Date_Time = `Date-Time (EST/EDT)`)

#082024 - has data from 7/24 to 8/24
df4<-fread("HOBO_Data\\raw_data\\082024_ASHC_HOBO.csv",encoding = "UTF-8")%>%  # update this csv when new data comes in from the new HOBO
  dplyr::rename(Temperature = `Temperature`) %>%
  dplyr::rename(Date_Time = `Date-Time (EDT)`) %>%
  dplyr::select( -c( "Button Down", "Button Up", "End of File", "Started Offset"))

#102024 - has data from 8/26/24 to 10/21/2024
df5<-read_csv("HOBO_Data\\raw_data\\102024_ASHC_HOBO.csv", col_names = TRUE)%>%  # update this csv when new data comes in from the new HOBO
  dplyr::rename(Temperature = `Temperature   (°C)`) %>%
  dplyr::rename(Date_Time = `Date-Time (EDT)`) %>%
  dplyr::select( -c( "Button Down", "Button Up", "End of File", "Started Offset"))

#For some reason the HOBO is only downloading new data so this is a bit excessive but were going to trouble shoot it next time were out. 
#112024
df6<-read_csv("HOBO_Data\\raw_data\\112024_ASHC_HOBO.csv", col_names = TRUE)%>%  # update this csv when new data comes in from the new HOBO
  dplyr::rename(Temperature = `Temperature   (°C)`) %>%
  dplyr::rename(Date_Time = `Date-Time (EST/EDT)`) %>%
  dplyr::select( -c( "Button Down", "Button Up", "End of File", "Started Offset","Stopped"))

#The HOBO did not collect data over winter - the log stopped for some reason. 
#3/5/25- present
df7<-read_csv("HOBO_Data\\raw_data\\052025_ASHC_HOBO.csv", col_names = TRUE)%>%  
  dplyr::rename(Temperature = `Temperature`) %>%
  dplyr::rename(Date_Time = `Date-Time (EST/EDT)`) %>% 
  dplyr::select( -c( "Button Down", "Button Up", "End of File", "Started Offset","Host Connected"))

ASHC_HOBO <- rbind(df3,df4,df5,df6,df7)

#ASHC_HOBO <- read_csv("HOBO_Data\\raw_data\\112024_ASHC_HOBO.csv", col_names = TRUE)   

as.data.frame(ASHC_HOBO)

## removing unneeded columns with NAs

#ASHC_HOBO <- ASHC_HOBO %>%
 # dplyr::select( -c( "Button Down", "Button Up", "End of File", "Started Offset", "Host Connected"))

ASHC_HOBO <- na.omit(ASHC_HOBO)


#Change column names

if ("Date-Time (EDT)" %in% names(ASHC_HOBO) && "Temperature (°C)" %in% names(ASHC_HOBO)) {
  ASHC_HOBO <- ASHC_HOBO %>%
    rename(
      Date_Time = `Date-Time (EDT)`,
      Temperature = `Temperature  (°C)`
    )
} else {
  warning("One or more columns to rename do not exist.")
}

ASHC_HOBO

ASHC_HOBO$Date_Time <- as.character(ASHC_HOBO$Date_Time)
date_time <- strsplit(ASHC_HOBO$Date_Time, " ")  # Split at the space
ASHC_HOBO$Date <- sapply(date_time, "[[", 1)  # Extract date
ASHC_HOBO$Time <- sapply(date_time, function(x) {
  if(length(x) >= 2) {
    x[[2]]  # Extract the second element if it exists
  } else {
    NA  # Assign NA if the vector is too short
  }
})
print(ASHC_HOBO)


#### Lets look at the data 

ggplot(ASHC_HOBO, aes(Date_Time, Temperature)) + geom_point()


# Hourly Means 

ASHC_means <- ASHC_HOBO %>%
  mutate(Date_Time = as.POSIXct(substr(Date_Time, 1, 13), format = "%m/%d/%Y %H")) %>% # Adjust the date format
  tidyr::pivot_longer(cols = c("Temperature"), names_to = "variable", values_to = "value") %>%
  dplyr::group_by(Date_Time, variable) %>%
  dplyr::summarise(mean_value = mean(value),sd_value = sd(value),se_value = sd(value) / sqrt(n())) 

View(ASHC_means)
```

```{r}
#ASHC_plot<- ASHC_means %>%
#    ggplot(aes(Date_Time, mean_value))+ geom_point() + 
#    geom_line(size = 0.2, position=position_dodge(.4))+
#    #scale_color_manual(values = "grey38")+
#              scale_shape_manual(values=c(21, 22, 24, 25)) + 
#              scale_fill_manual(values=c("#CC79A7", "#D55E00", "#009E73", "#0072B2")) + 
#              geom_errorbar(aes(ymin=(mean_value)-(se_value), 
#                                ymax=(mean_value)+(se_value)), 
#                            width=0,position=position_dodge(.4))+
#     ggtitle("Ash Creek, CT ") +
              #labs(x = "Time", y = "Temperature") +
#               labs(x = "", y = "") + 
#              theme_classic() + theme(axis.text= element_text(size=12), axis.title = element_text(size= 12))+
#   scale_x_datetime(date_labels = "%b/%Y", date_breaks = "1 month", limits = as.Date(c('2023-06-01','2024-04-01'))) 
#ASHC_plot


ASHC_plot <- ASHC_means %>%
    mutate(Date_Time = as.POSIXct(Date_Time)) %>%
    ggplot(aes(Date_Time, mean_value)) + 
    geom_point() + 
    geom_line(size = 0.2, position = position_dodge(.4)) +
    scale_shape_manual(values = c(21, 22, 24, 25)) + 
    scale_fill_manual(values = c("#CC79A7", "#D55E00", "#009E73", "#0072B2")) + 
    geom_errorbar(aes(ymin = mean_value - se_value, 
                      ymax = mean_value + se_value), 
                  width = 0, position = position_dodge(.4)) +
    ggtitle("Ash Creek, CT") +
    labs(x = "", y = "") + 
    theme_classic() + 
    theme(axis.text = element_text(size = 25), axis.title = element_text(size = 12),axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1) ) +
    scale_x_datetime(date_labels = "%b/%Y", 
                     date_breaks = "1 month", 
                     limits = as.POSIXct(c('2023-06-01', '2025-11-30')))+geom_hline(yintercept = 20, color = "red", linetype = "solid", size = 1)+
  geom_hline(yintercept = 16, color = "blue", linetype = "solid", size = 1)
ASHC_plot

pdf(paste0(path_out,"ASHC_HOBO.pdf"), height = 7, width = 14)
print(ASHC_plot)

```


#### juvenile growth Fence Creek ###
```{r}
# we just need june and july data so we are going to subset that out
ASHC_jj <- ASHC_means %>% filter(Date_Time > '2024-06-01 00:00:00' & Date_Time < '2024-07-10 00:00:00' )

ASHC_plot_juv <- ASHC_jj %>%
    mutate(Date_Time = as.POSIXct(Date_Time)) %>%
    ggplot(aes(Date_Time, mean_value)) + 
    geom_point() + 
    geom_line(size = 0.2, position = position_dodge(.4)) +
    scale_shape_manual(values = c(21, 22, 24, 25)) + 
    scale_fill_manual(values = c("#CC79A7", "#D55E00", "#009E73", "#0072B2")) + 
    geom_errorbar(aes(ymin = mean_value - se_value, 
                      ymax = mean_value + se_value), 
                  width = 0, position = position_dodge(.4)) +
    ggtitle("Ash Creek, CT") +
    labs(x = "", y = "") + 
    theme_classic() + 
    theme(axis.text = element_text(size = 12), axis.title = element_text(size = 12)) +
    scale_x_datetime(date_labels = "%b/%Y", 
                     date_breaks = "1 month", 
                     limits = as.POSIXct(c('2024-06-01', '2024-07-15')))

ASHC_plot_juv


FENC_jj <- FENC_means %>% filter(Date_Time > '2024-06-01 00:00:00' & Date_Time < '2024-07-10 00:00:00' )

FENC_plot_juv <- FENC_jj %>%
    mutate(Date_Time = as.POSIXct(Date_Time)) %>%
    ggplot(aes(Date_Time, mean_value)) + 
    geom_point() + 
    geom_line(size = 0.2, position = position_dodge(.4)) +
    scale_shape_manual(values = c(21, 22, 24, 25)) + 
    scale_fill_manual(values = c("#CC79A7", "#D55E00", "#009E73", "#0072B2")) + 
    geom_errorbar(aes(ymin = mean_value - se_value, 
                      ymax = mean_value + se_value), 
                  width = 0, position = position_dodge(.4)) +
    ggtitle("Fenc Creek, CT") +
    labs(x = "", y = "") + 
    theme_classic() + 
    theme(axis.text = element_text(size = 12), axis.title = element_text(size = 12)) +
    scale_x_datetime(date_labels = "%b/%Y", 
                     date_breaks = "1 month", 
                     limits = as.POSIXct(c('2024-06-01', '2024-07-15')))

FENC_plot_juv

```

```{r}
ASHC_plot1 <- ASHC_plot + theme(axis.text.x = element_blank())

CT_plot<-ggarrange(ASHC_plot1, FENC_plot,nrow=2) %>%
  annotate_figure(left=text_grob("Temperature", rot=90, size = 30), bottom = text_grob("Time", size = 30))
CT_plot

pdf(paste0(path_out,"CT_HOBO.pdf"), height = 12, width = 14)
print(CT_plot)

```


## Gold Star Beach
```{r}
GOLD_HOBO <- read_csv("HOBO_Data\\raw_data\\092024_GOLD_HOBO.csv", col_names = TRUE)   

as.data.frame(GOLD_HOBO)

View(GOLD_HOBO)

names(GOLD_HOBO)
#Change column names

GOLD_HOBO <- GOLD_HOBO %>%
  dplyr::rename(Temperature = `Temperature   (°C)`) %>%
  dplyr:: rename(Date_Time = `Date-Time (EST/EDT)`)
GOLD_HOBO

GOLD_HOBO$Date_Time <- as.character(GOLD_HOBO$Date_Time)
date_time <- strsplit(GOLD_HOBO$Date_Time, " ")  # Split at the space
GOLD_HOBO$Date <- sapply(date_time, "[[", 1)  # Extract date
GOLD_HOBO$Time <- sapply(date_time, function(x) {
  if(length(x) >= 2) {
    x[[2]]  # Extract the second element if it exists
  } else {
    NA  # Assign NA if the vector is too short
  }
})
print(GOLD_HOBO)

## removing unneeded columns with NAs

GOLD_HOBO <- GOLD_HOBO %>%
  dplyr::select( -c("Host Connected", "Water Detect", "Button Down", "Button Up", "End of File"))

GOLD_HOBO <- na.omit(GOLD_HOBO)

#### Lets look at the data 

ggplot(GOLD_HOBO, aes(Date_Time, Temperature)) + geom_point()


# Hourly Means 

GOLD_means <- GOLD_HOBO %>%
  mutate(Date_Time = as.POSIXct(substr(Date_Time, 1, 13), format = "%m/%d/%Y %H")) %>% # Adjust the date format
  tidyr::pivot_longer(cols = c("Temperature"), names_to = "variable", values_to = "value") %>%
  dplyr::group_by(Date_Time, variable) %>%
  dplyr::summarise(mean_value = mean(value),sd_value = sd(value),se_value = sd(value) / sqrt(n())) 

GOLD_means
## Including Plots

```
```{r}


GOLD_plot <- GOLD_means %>%
    mutate(Date_Time = as.POSIXct(Date_Time)) %>%
    ggplot(aes(Date_Time, mean_value)) + 
    geom_point() + 
    geom_line(size = 0.2, position = position_dodge(.4)) +
    scale_shape_manual(values = c(21, 22, 24, 25)) + 
    scale_fill_manual(values = c("#CC79A7", "#D55E00", "#009E73", "#0072B2")) + 
    geom_errorbar(aes(ymin = mean_value - se_value, 
                      ymax = mean_value + se_value), 
                  width = 0, position = position_dodge(.4)) +
    ggtitle("Gold Star Beach") +
    labs(x = "", y = "") + 
    theme_classic() + 
    theme(axis.text = element_text(size = 12), axis.title = element_text(size = 12)) +
    scale_x_datetime(date_labels = "%b/%Y", 
                     date_breaks = "1 month", 
                     limits = as.POSIXct(c('2023-06-01', '2024-07-01')))
GOLD_plot

pdf(paste0(path_out,"GOLD_HOBO.pdf"), height = 7, width = 14)
print(GOLD_plot)
```
You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

```{r}
sessionInfo()
```